name: Action Practice


on:
  push:
  schedule:
   - cron: "0 16 * * *"
  

env:
  TZ: Asia/Shanghai

jobs:
  # a single job
  a-job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3
        id: setup-ffmpeg
        with:
         ffmpeg-version: release
      # Target architecture of the
         ffmpeg-path: videos/
         architecture: ''
      # Linking type of the binaries. Use "shared" to download shared binaries and 
      # "static" for statically linked ones. Shared builds are currently only available
      # for windows releases. Defaults to "static"
         linking-type: static
      # As of version 3 of this action, builds are no longer downloaded from GitHub
      # except on Windows: https://github.com/GyanD/codexffmpeg/releases.
         github-token: ${{ github.server_url == 'https://github.com' && github.token || '' }}
      
      # A specific version to download, may also be "release" or a specific version
      # like "6.1.0".
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          pip3 install requests huggingface_hub
      - name: Run
        run: python3 ./run.py --token ${{ secrets.HF_TOKEN }}


      - name: Commit
        env:
          GIT_NAME: GitHub Actions[Bot]
          GIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        
        run: |
          git config --local user.name $GIT_NAME
          git config --local user.email $GIT_EMAIL
          git pull
           
          
          git reset --mixed master
          git add .
          git commit -m "Github action update at `date '+%Y-%m-%d %H:%M:%S'`."
          git push
